@startuml EstadoDelDominio

hide empty description
skinparam classAttributeIconSize 0
skinparam classOperationIconSize 0

' estados
state "Llegar Al Comedor" as llegar
state "Verificar Disponibilidad Del Sevicio" as verificar
state "Formarse Para El Control De Acceso" as acceder
state "Recibir Alimentos" as recibir
state "Dirgirise La Espacio Destinado Para Comer" as comer
state "Recoger Utensilios Y Sobras" as recoger
state "Depossitar Sobras En La Basura" as botar
state "Depositar Utensilios En El Area Designada" as depositar
state "Retirarse Del Comedor" as retirarse

' Relaciones
[*] --> llegar
llegar --> verificar
verificar --> retirarse : No Disponible
verificar --> acceder
acceder --> retirarse : No Autorizado
acceder --> recibir
recibir --> comer
comer --> recoger
recoger --> botar
botar --> depositar
depositar --> retirarse
retirarse --> [*]

@enduml