@startuml EstadoDelDominio

hide empty description
skinparam classAttributeIconSize 0
skinparam classOperationIconSize 0

' estados
state "Llegar Al Comedor" as llegar
state "Verificar Disponibilidad Del Sevicio" as verificar
state "Formarse Para El Control De Acceso" as acceder
state "Recibir Alimentos" as recibir
state "comer" as comer
state "Recoger Utensilios" as recoger
state "Retirarse Del Comedor" as retirarse

' Relaciones
[*] --> llegar
llegar --> verificar
verificar --> retirarse : No Disponible
verificar --> acceder
acceder --> retirarse : No Autorizado
acceder --> recibir
recibir --> comer
comer --> recoger
recoger --> retirarse
retirarse --> [*]

@enduml