@startuml DiagramaDeCasosDeUso

title Casos De Uso Comedor Universitario
skinparam actorStyle awesome
left to right direction

actor Comensal
actor Administrador
actor :Usuario del Sistema: as user


rectangle " "{

    usecase (Inicio de Sesión) as inicio

    usecase (Registrar Comensal) as registro_usuario
    usecase (Registrar Acceseso) as registro_acceso
    usecase (Asignar Turno) as asignacion
    usecase (Consultar Menus) as menus_consultar
    usecase (Selecionar Menu) as menus_selecionar

   
    usecase (Gestionar Insumos ) as insumos
    usecase (Gestionar Menus) as gestion 
    usecase (Generar Reportes) as reporte
    usecase (Registrar Personal) as registro_personal

}

user <|-- Comensal
user <|-- Administrador

user --> inicio
inicio ..> registro_usuario : Include
inicio ..> registro_personal : Include


Comensal --> asignacion
Comensal --> menus_selecionar

menus_selecionar ..> menus_consultar : Include
asignacion ..>  registro_acceso : Include


Administrador --> insumos
Administrador --> gestion
Administrador --> reporte

@enduml